---
new_page_extension: md
auto_deploy: false
admin_path: ""
webhook_url:
sections:
  - type: heading
    label: Blog Post
  - type: directory
    path: content/english/blog
    label: Post (en)
    create: documents
    match: "**/*"
    templates:
      - post
  - type: directory
    path: content/chinese/blog
    label: Post (zh)
    create: documents
    match: "**/*"
    templates:
      - post
  - type: heading
    label: Author
  - type: directory
    path: content/english/author
    label: Author (en)
    create: documents
    match: "**/*"
    templates:
      - author
  - type: directory
    path: content/chinese/author
    label: Author (zh)
    create: documents
    match: "**/*"
    templates:
      - author
  - type: heading
    label: Solution
  - type: directory
    path: content/english/solution
    label: Solution (en)
    create: documents
    match: "**/*"
    templates:
      - solution
  - type: directory
    path: content/chinese/solution
    label: Solution (zh)
    create: documents
    match: "**/*"
    templates:
      - solution
  - type: heading
    label: Product
  - type: directory
    path: content/english/product
    label: Product (en)
    create: documents
    match: "**/*"
    templates:
      - product
  - type: directory
    path: content/chinese/product
    label: Product (zh)
    create: documents
    match: "**/*"
    templates:
      - product
  - type: directory
    path: content/chinese/solution
    label: Product (zh)
    create: documents
    match: "**/*"
    templates:
      - product
  # - type: heading
  #   label: Notice
  # - type: directory
  #   path: content/english/notice
  #   label: Notice (en)
  #   create: all
  #   match: "**/*"
  #   templates:
  #     - notice
  # - type: directory
  #   path: content/chinese/notice
  #   label: Notice (zh)
  #   create: all
  #   match: "**/*"
  #   templates:
  #     - notice
  - type: heading
    label: Teacher
  - type: directory
    path: content/english/teacher
    label: Teacher (en)
    create: all
    match: "**/*"
    templates:
      - teacher
  - type: directory
    path: content/chinese/teacher
    label: Teacher (zh)
    create: all
    match: "**/*"
    templates:
      - teacher
  - type: heading
    label: Event
  - type: directory
    path: content/english/event
    label: Event (en)
    create: all
    match: "**/*"
    templates:
      - event
  - type: directory
    path: content/chinese/event
    label: Event (zh)
    create: all
    match: "**/*"
    templates:
      - event
  - type: heading
    label: Others Pages
  - type: directory
    path: content/english/about
    label: About (en)
    create: none
    match: "*"
  - type: directory
    path: content/chinese/about
    label: About (zh)
    create: none
    match: "*"
  - type: directory
    path: content/english/contact
    label: Contact (en)
    create: none
    match: "*"
  - type: directory
    path: content/chinese/contact
    label: Contact (zh)
    create: none
    match: "*"
  - type: directory
    path: content/english/pages
    label: Created Pages (en)
    create: documents
    match: "**/*"
    templates:
      - new-page
  - type: directory
    path: content/chinese/pages
    label: Created Pages (zh)
    create: all
    match: "**/*"
    templates:
      - new-page
  - type: directory
    path: content/english
    label: All Pages (en)
    create: all
    match: "**/*"
    templates:
      - new-page
  - type: directory
    path: content/chinese
    label: All Pages (zh)
    create: all
    match: "**/*"
    templates:
      - new-page
  - type: heading
    label: Data
  - type: directory
    path: data/zh
    label: Data (zh)
    create: all
    match: "**/*"
  - type: directory
    path: data/en
    label: Data (en)
    create: all
    match: "**/*"
  - type: directory
    path: i18n
    label: i18n
    create: documents
    match: "**/*"
  - type: heading
    label: Configuration
  - type: directory
    path: exampleSite
    label: Configuration
    create: all
    match: "*.toml"
    new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
zhont_matter_path: ""
use_zhont_matter_path: false
file_template: ":filename:"
build:
  preview_env:
    - HUGO_ENV=staging
    - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 1313 --bind 0.0.0.0 --renderToDisk -d public
version: 0.58.2
